### DISCUSSION TITLE
Make `youtube.com` issue automatically duplicate

### DISCUSSION THREAD

**Discussion by Nomes77** [uBlockOrigin/uAssets#20404] [General] [answered]
A solution to ban invalid issue.
1. Install https://github.com/riyadhalnur/issuelabeler
2. Put the following in `.github/labeler.yml`
```
excludeLabels:
  - ongoing 
custom:
  - location: title
    keywords:
      - 'youtube'
      - 'facebook'
      - 'twitch'
    labels:
      - duplicate
```
3. Make `.github/workflows/label-commenter.yml` and put the following in it:
```
name: Label Commenter

on:
  issues:
    types:
      - labeled

permissions:
  contents: read
  issues: write

jobs:
  comment:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master # Set your default branch

      - name: Label Commenter
        uses: peaceiris/actions-label-commenter@v1.10.0
```
4. Put the following in `.github/label-commenter-config.yml`:
```
labels:
  - name: duplicate
    labeled:
      issue:
        body:  |
            @{{ issue.user.login }}, please follow the issue template.
            > This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
        action: close
```

**Comment by MasterKia** [comment]
@gorhill

**Reply by gorhill** [reply, marked as answer]
Giving it a try: https://github.com/uBlockOrigin/uAssets/commit/791500ccaf0097adbafa8929e501e9348c2e0787

Still need to see if it will work as expected.

**Reply by krystian3w** [reply]
Based on #21625 / #21624 actions works too slow/rare at day.

**Comment by JohnyP36** [comment]
The code 
```yml
excludeLabels:
  - pinned
custom:
  - location: title
    keywords:
      - 'youtube'
      - 'facebook'
      - 'twitch'
    labels:
      - duplicate
```
may close the `ALL twich.tv / facebook.com issues` as they are not pinned.
