### ISSUE TITLE
filecr.com

### ISSUE THREAD

**Issue by realodix** [uBlockOrigin/uAssets#10238]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

https://filecr.com/windows/microsoft-office/?id=6309061920

### Describe the issue

Click Download Torrent

### Screenshot(s)

![noname-crop](https://user-images.githubusercontent.com/1314456/137621385-6e62809b-377c-4263-b95a-b5f0df027c5d.png)

### Configuration

<details>

```yaml
browserFlavor: ublock webext devbuild firefox user_stylesheet html_filtering mozilla
browserVersion: 93
extensionName: uBlock Origin
extensionVersion: 1.38.7b3
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
listset: 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    adguard-generic: 
      filters used/total: 58630 / 59351
      updated last/next (days): -0.08 / 3.92
    adguard-annoyance: 
      filters used/total: 44870 / 46197
      updated last/next (days): -0.96 / 3.04
    adguard-social: 
      filters used/total: 14404 / 14420
      updated last/next (days): -0.96 / 3.04
  default: 
    ublock-filters: 
      filters used/total: 27089 / 29716
      updated last/next (days): -0.85 / 3.15
    ublock-badware: 
      filters used/total: 3013 / 3014
      updated last/next (days): -0.96 / 3.04
    ublock-privacy: 
      filters used/total: 171 / 171
      updated last/next (days): -0.96 / 3.04
    ublock-abuse: 
      filters used/total: 67 / 67
      updated last/next (days): -0.96 / 3.04
    ublock-unbreak: 
      filters used/total: 1691 / 1691
      updated last/next (days): -0.96 / 3.04
    easylist: 
      filters used/total: 58939 / 59591
      updated last/next (days): -0.88 / 3.12
    easyprivacy: 
      filters used/total: 25353 / 25502
      updated last/next (days): -0.96 / 3.04
trustedset: 
  added: [array of 1 redacted]
  removed: 
    about-scheme
filterset: [array of 1 redacted]

```
</details>
