### ISSUE TITLE
dofusports.xyz [popup ads on click]

### ISSUE THREAD

**Issue by jjohns71** [uBlockOrigin/uAssets#10277]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`http://dofusports.xyz/mlb/houston-astros-at-boston-red-sox-away/`

### Describe the issue

Click any links at top of page `NBA`, `NHL`, etc. and popup window spawns

### Configuration

<details>

```yaml
browserFlavor: ublock webext devbuild chromium user_stylesheet
browserVersion: 95
extensionId: cgbcahbpdhpcegmbfconppldiemgcoii
extensionName: uBlock Origin
extensionVersion: 1.38.7b5
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  autoCommentFilterTemplate: {{url}}
  filterAuthorMode: true
listset: 
  added: 
    ublock-annoyances: 
      filters used/total: 4263 / 4271
      updated last/next (days): -0.01 / 3.99
  default: 
    easylist: 
      filters used/total: 59755 / 59760
      updated last/next (days): -0.01 / 3.99
    easyprivacy: 
      filters used/total: 25378 / 25385
      updated last/next (days): -0.01 / 3.99
    plowe-0: 
      filters used/total: 3132 / 3676
      updated last/next (days): -0.01 / 12.99
    ublock-abuse: 
      filters used/total: 67 / 67
      updated last/next (days): -0.01 / 3.99
    ublock-badware: 
      filters used/total: 2992 / 3047
      updated last/next (days): -0.01 / 3.99
    ublock-filters: 
      filters used/total: 29189 / 29288
      updated last/next (days): -0.01 / 3.99
    ublock-privacy: 
      filters used/total: 173 / 178
      updated last/next (days): -0.01 / 3.99
    ublock-unbreak: 
      filters used/total: 1636 / 1681
      updated last/next (days): -0.01 / 3.99
    urlhaus-1: 
      filters used/total: 13701 / 13701
      updated last/next (days): -0.01 / 0.99
filterset: [empty]
switchRuleset: 
  added: [array of 1 redacted]

```
</details>
