### ISSUE TITLE
incorrect blocking

### ISSUE THREAD

**Issue by loveqianool** [uBlockOrigin/uAssets#10348]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

NSFW
`https://www.54647.io/game.html?id=1`

### Describe the issue

When ublock enabled, not work properly

### Configuration

<details>

```yaml
browserFlavor: ublock webext devbuild chromium user_stylesheet
browserVersion: 97
extensionId: cgbcahbpdhpcegmbfconppldiemgcoii
extensionName: uBlock Origin
extensionVersion: 1.38.7b9
modifiedUserSettings: 
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
listset (total-discarded, last updated): 
  default: 
    CHN-0: 26039-83, 2d.12h.29m
    easylist: 59846-9, 2d.12h.25m
    easyprivacy: 25412-33, 2d.12h.23m
    plowe-0: 3675-546, 9d.18h.31m
    ublock-abuse: 67-0, 2d.12h.21m
    ublock-badware: 3055-53, 2d.12h.27m
    ublock-filters: 29442-95, 2d.8h.19m
    ublock-privacy: 177-1, 2d.4h.15m
    ublock-unbreak: 1679-41, 2d.8h.17m
    urlhaus-1: 7740-0, 19h.43m
trustedset: 
  added: [array of 1 redacted]
filterset: [array of 5 redacted]

```
</details>
