### ISSUE TITLE
thenerdstash.com

### ISSUE THREAD

**Issue by theinstantmatrix** [uBlockOrigin/uAssets#10384]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://thenerdstash.com/guardians-of-the-galaxy-how-to-get-gamoras-chosen-daughter-outfit/`

### Describe the issue

Anti-Adblock Script - Admiral

### Screenshot(s)

![image](https://user-images.githubusercontent.com/24980766/140100537-7304cdcc-81d1-484e-919a-ba93dc3bf37a.png)

### Notes

Suggested filter: `thenerdstash.com##+js(acis, document.createElement, admiral)`

### Configuration

<details>

```yaml
browserFlavor: ublock webext devbuild firefox user_stylesheet html_filtering mozilla
browserVersion: 94
extensionName: uBlock Origin
extensionVersion: 1.38.7b12
modifiedUserSettings: 
  advancedUserEnabled: true
  alwaysDetachLogger: false
  colorBlindFriendly: true
modifiedHiddenSettings: 
  filterAuthorMode: true
listset (total-discarded, last updated): 
  added: 
    adguard-spyware-url: 340-0, now
    adguard-annoyance: 46735-2908, now
    fanboy-cookiemonster: 20318-120, now
    ublock-annoyances: 4291-5, now
    KOR-1: 7903-3, now
  default: 
    ublock-filters: 30131-37, now
    ublock-badware: 3167-1, now
    ublock-privacy: 176-0, now
    ublock-abuse: 67-0, now
    ublock-unbreak: 1694-0, now
    easylist: 60306-511, now
    easyprivacy: 25447-213, now
    urlhaus-1: 7471-0, now
    plowe-0: 3677-2, now
trustedset: 
  added: [array of 1 redacted]
filterset: [array of 12 redacted]

```
</details>
