### ISSUE TITLE
w3schools.com

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#12688]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.w3schools.com/css/tryit.asp?filename=trycss_form_padding`

### Describe the issue

Page added "new" navigation = seo for searches only unfortunately.

> ![obraz](https://user-images.githubusercontent.com/35370833/162629737-3410da8a-f66f-473d-8538-b1b1132bb690.png)

They is hidden with legacy hide Placeholder metho also they css generate nasty / ugly grayish 3 triangles:

> ![obraz](https://user-images.githubusercontent.com/35370833/162629812-7c2fc311-305e-466d-b32d-bbaee9ed1461.png)

### Screenshot(s)

Moved to description

### uBlock Origin version

1.42.2

### Browser name and version

Firefox Dev 100.0b3

### Settings

- enabled uBO Annoyances

### Notes

releated: https://github.com/uBlockOrigin/uAssets/issues/1658

https://github.com/uBlockOrigin/uAssets/commit/86cee99591b83cca21fea72b61fc77e4471ef9a6

https://github.com/uBlockOrigin/uAssets/blob/e8f483ecb20f0b68d7487c4801b7ab0bc3c0c6fd/filters/filters-2020.txt#L2697-L2699

So I recommend add:

`w3schools.com###breadcrumb:matches-path(/tryit.asp)`

or

`###tryitLeaderboard ~  #breadcrumb`

> ![obraz](https://user-images.githubusercontent.com/35370833/162630016-21bb2390-446c-4432-97b3-8f8c72099ba9.png)

Also FYI @Yuki2718 - AdGuard use similar hotfix, may need update if if no one has maintained these filters recently in AG Base:

> ```
> ! https://github.com/AdguardTeam/AdguardFilters/issues/5909
> w3schools.com#$##tryitLeaderboard ~ .trytopnav { top: 0!important; }
> w3schools.com#$##tryitLeaderboard ~ #container { top: 40px!important; }
> ```

**Comment by u-RraaLL** [comment]
>     w3schools.com###breadcrumb:matches-path(/tryit.asp)

FYI, `:matches-path()` should be at the beginning as per https://github.com/gorhill/uBlock/wiki/Procedural-cosmetic-filters#subjectmatches-patharg

**Comment by krystian3w** [comment]
I need proves form console about lag if they moved to top.

The best will be drop filter if path is on middle or at end in uBo 1.42.4.

Also AG don't like `:matches-path(,program,)` / `:matches-path(,software,)`

like url:

`github.com/uBlockOrigin/uAssets/issues/12688/ping,programy,software,topic`

**Comment by krystian3w** [comment]
@Yuki2718 smartphones and very small screens hide that navigation - very rare demo still no have that seo optimized navigation.

I no have solution for uBO - too rare check `:matches-css(display: none)`

but AG support media query (uBo may never - AG base demo maybe was fixed with hard write scriptlets but AG faster made CSS):

```css
w3schools.com#$#@media (max-width: 727px) { #tryitLeaderboard ~ .trytopnav { top: 0!important; } }
w3schools.com#$#@media (max-width: 727px) { #tryitLeaderboard ~ #container { top: 40px!important; }
```


Also reccommend retest value `79-84px` on your PC, because you hide bottom "border" on "run" button (2px rows are hiden on Windows) [corners no longer round] - something like cssNazi:

`w3schools.com###tryitLeaderboard ~ #container:style(top: 84px!important;)`

**Comment by AdamWr** [comment]
I guess that it's okay to add these rules, but do these exceptions(`#@$#`) are really needed?

**Comment by Yuki2718** [comment]
> are really needed?

Not needed, just wanted to avoid overwrapping.

**Comment by krystian3w** [comment]
Page started load ads as sidebar:

`https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_command_type`

https://github.com/user-attachments/assets/c2494787-e4e8-42e0-8443-6c31a7cb6a5e

<img width="391" height="120" alt="Image" src="https://github.com/user-attachments/assets/b3bf9b38-660d-4bb5-890f-8630f175977e" />:

<details> 

```css
/*Oppsett for Sparteo Ads*/
#mainLeaderboard {height:250px}
#footer-skyscraper {display:none;}
#vidpos {display:none;}
.sidesection:has(#upperfeatureshowcaselink) {margin-top:0px !important;}
#bottomads {display:none;}
#exercise_main_leaderboard {display:none;}
#stickyadcontainer {z-index: 1;}
@media screen and (min-width:1024px) {
  #tryitLeaderboard {display:none !important;}
  .trytopnav {top:0px !important;}
  #container {top:44px !important;}
  .trytopnav, #container {width: calc(100% - 250px) !important; } 
}
```

</details>

maybe unstable:

```adb
||w3schools.com/lib/sparteo.css$stylesheet,1p,important,redirect=noop.css
```
