### ISSUE TITLE
fivethirtyeight.com: ads

### ISSUE THREAD

**Issue by wavygecko** [uBlockOrigin/uAssets#14447]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://fivethirtyeight.com/features/can-tim-ryan-really-win-ohios-senate-race/`

### Category

ads

### Describe the issue

Ad container `##.ad-incontent`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/110956608/185727238-3889dcd3-17a3-44ba-aaa9-410c7e4cc3cf.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 103
listset (total-discarded, last updated): 
  added: 
    fanboy-cookiemonster: 40236-86, 6h.2m
  default: 
    user-filters: 119-0, never
    ublock-filters: 33231-84, 6h.2m
    ublock-badware: 4263-0, 6h.2m
    ublock-privacy: 247-2, 6h.2m
    ublock-abuse: 76-0, 6h.2m
    ublock-unbreak: 1842-1, 6h.2m
    ublock-quick-fixes: 417-0, 6h.2m
    easylist: 69597-611, 6h.2m
    easyprivacy: 27390-578, 6h.2m
    urlhaus-1: 4622-0, 6h.2m
    plowe-0: 3632-3, 6h.2m
filterset (user): [array of 116 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 617 ms
  maxAssetCacheWait: 333 ms
popupPanel: 
  blocked: 15
  blockedDetails: 
    fivethirtyeight.com: 4
    espn.com: 3
    go.com: 1
    googletagmanager.com: 1
    myfonts.net: 2
    onetrust.com: 1
    taboola.com: 1
    webcontentassessor.com: 2
```
</details>
