### ISSUE TITLE
features.texasmonthly.com: ads

### ISSUE THREAD

**Issue by wavygecko** [uBlockOrigin/uAssets#14446]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://features.texasmonthly.com/editorial/still-life/`

### Category

ads

### Describe the issue

Ad containers `##.acm-ad-tag-unit`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/110956608/185727201-53f84bca-034c-4464-9c0e-afe51daaa864.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 103
listset (total-discarded, last updated): 
  added: 
    fanboy-cookiemonster: 40236-86, 6h
  default: 
    user-filters: 120-0, never
    ublock-filters: 33231-84, 6h
    ublock-badware: 4263-0, 6h
    ublock-privacy: 247-2, 6h
    ublock-abuse: 76-0, 6h
    ublock-unbreak: 1842-1, 6h
    ublock-quick-fixes: 417-0, 6h
    easylist: 69597-611, 6h
    easyprivacy: 27390-578, 6h
    urlhaus-1: 4622-0, 6h
    plowe-0: 3632-3, 6h
filterset (user): [array of 117 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 617 ms
  maxAssetCacheWait: 333 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    disqus.com: 1
    googletagmanager.com: 1
    googletagservices.com: 1
    jwpltx.com: 1
    moatads.com: 1
    parsely.com: 2
    sharethis.com: 2
    wp.com: 2
```
</details>
