### ISSUE TITLE
outlook.live.com: breakage

### ISSUE THREAD

**Issue by Vidorr** [uBlockOrigin/uAssets#17413]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://outlook.live.com/mail/0/`

### Category

breakage

### Description

Filter is blocking out all emails in my inbox. The page refreshes occasionally due to it reaching the bottom of the loaded email list. This causes emails to show up again for a split second before getting removed again by Ublock. I have disabled cosmetic filtering for this page and everything works fine after.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.0
Chromium: 111
filterset (summary): 
  network: 88588
  cosmetic: 39739
  scriptlet: 17496
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 65126-46, 2d.3h.30m
    easyprivacy: 30755-1175, 2d.3h.29m
    plowe-0: 3751-935, 2d.3h.28m
    ublock-abuse: 78-0, 2d.3h.26m
    ublock-badware: 6080-114, 2d.3h.24m
    ublock-filters: 33148-97, 2d.3h.23m
    ublock-privacy: 302-2, 2d.3h.22m
    ublock-quick-fixes: 455-14, 44m
    ublock-unbreak: 1945-42, 2d.3h.20m
    urlhaus-1: 6786-0, 43m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 153 ms (selfie)
  maxAssetCacheWait: 87 ms
popupPanel: 
  blocked: 78
  blockedDetails: 
    3lift.com: 18
    adnxs.com: 24
    googlesyndication.com: 4
    microsoft.com: 6
    office.net: 6
    taboola.com: 18
    yahoo.com: 2
```
</details>

**Comment by mapx-** [comment]
- open the uBO's logger: https://github.com/gorhill/uBlock/wiki/The-logger
- repeat the steps to get the issue
- go back into the uBO's logger and then copy and paste here all blocked requests

**Comment by stephenhawk8054** [comment]
Hmmm... Where is this filter? I don't see it in any of the main lists

```adb
##div[data-focuszone-id] + div > button > div > img[class][src$="/leftNavUpsellIcons/premium-diamond-01.svg"]:upward(2)
```

These filters are only in `ublock filters - annoyances` list

```adb
outlook.live.com##div[class][tabindex="-1"][role=region][aria-label][data-min-width][data-max-width] ~ div[class][data-max-width="2400"] + div[class]
outlook.live.com###MainModule + div[class] > div[style^="width"] > div > i[data-icon-name="OutlookLogo"]:upward(3)
outlook.live.com###MainModule div[data-max-width="2400"] + div[class]
```

but I don't see that list enabled in OP's configuration

```yaml
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 65126-46, 2d.3h.30m
    easyprivacy: 30755-1175, 2d.3h.29m
    plowe-0: 3751-935, 2d.3h.28m
    ublock-abuse: 78-0, 2d.3h.26m
    ublock-badware: 6080-114, 2d.3h.24m
    ublock-filters: 33148-97, 2d.3h.23m
    ublock-privacy: 302-2, 2d.3h.22m
    ublock-quick-fixes: 455-14, 44m
    ublock-unbreak: 1945-42, 2d.3h.20m
    urlhaus-1: 6786-0, 43m
```
