### ISSUE TITLE
biblestudytools.com: detection

### ISSUE THREAD

**Issue by Pinedal** [uBlockOrigin/uAssets#19547]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Full page anti-adblock pop-up. Scroll lock.

### URL(s) where the issue occurs.

`https://www.biblestudytools.com/library/`

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/143714552/809dec0c-6e03-419e-871c-9025fbdf0663)

### uBO version

1.51.0

### Browser name and version

Firefox 117.0

### Settings

```yaml
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 71400-5543, 34m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 93210-82331, 33m
  adguard-generic: 73474-6653, 36m
  adguard-spyware-url: 1192-68, 34m
  block-lan: 48-0, 34m
  curben-phishing: 164634-77, 34m
  curben-pup: 189-0, 34m
  adguard-social: 21299-708, 34m
  fanboy-thirdparty_social: 69-0, 34m
  fanboy-cookiemonster: 48342-337, 34m
  fanboy-social: 16223-25, 34m
  ublock-annoyances: 5400-8, 34m
  [5 lists not shown]: [too many]
filterset (user): [array of 200 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
```

### Notes

Issue seems to stem from:
Context: buy.tinypass.com
Url: `https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js`

Workable static filter which does not appear to break anything else:
`||cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js$script,domain=buy.tinypass.com`
