### ISSUE TITLE
gamepedia.com

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#2113]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

```
https://bindingofisaacrebirth.gamepedia.com/Keeper

https://terraria.gamepedia.com/Guns

https://enterthegungeon.gamepedia.com/Pea_Shooter
```

### Describe the issue

Calc width break website - after block element adblock warning

```css
#global-wrapper.with-siderail #content #bodyContent {
    box-sizing: border-box;
    float: left;
    width: calc(100% - 410px - 20px);
}
```

### Screenshot(s)

> ![obraz](https://user-images.githubusercontent.com/35370833/39395195-e759f34c-4adb-11e8-8264-92df476df970.png) |
> --- |

> ![obraz](https://user-images.githubusercontent.com/35370833/39395173-a3b08a5c-4adb-11e8-8712-c0c46bdba7e5.png) |
> --- |

> ![obraz](https://user-images.githubusercontent.com/35370833/39395181-c15c39fc-4adb-11e8-8d19-9a36096971df.png) |
> --- |

### Versions

- Browser/version: Firefox 59.0.2
- uBlock Origin version: 1.16.2

### Settings

-  uBO's default settings + Cookiemonster List

### Notes

```cpp
gamepedia.com###bodyContent:style(width:100%!important)
```

May works.
