### ISSUE TITLE
msn.com

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#5831]
`https://www.msn.com/en-us/entertainment/celebrity/60plus-stars-with-their-dear-old-dads/ss-AACQdnR?li=BBnb2gh`

No possible **select** and **drag** "title" under gallery.

---

Fix possible convert into `:style()` filter:

```css
.unselectable, .unselectable * {
   -moz-user-drag: auto !important;
   -moz-user-select: text !important;
}
```
