### ISSUE TITLE
lexlog.pl

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#5985]
`http://lexlog.pl/newsletter-a-rodo/`

blocked right click / select / maybe also copy by **generally** inline JS:

```js
<script type="text/javascript">
/*<![CDATA[*/
document.oncontextmenu = function() {
    return false;
};
document.onselectstart = function() {
    if (event.srcElement.type != "text" && event.srcElement.type != "textarea" && event.srcElement.type != "password") {
        return false;
    } else {
        return true;
    }
};
if (window.sidebar) {
    document.onmousedown = function(e) {
        var obj = e.target;
        if (obj.tagName.toUpperCase() == 'SELECT' ||
            obj.tagName.toUpperCase() == "INPUT" ||
            obj.tagName.toUpperCase() == "TEXTAREA" ||
            obj.tagName.toUpperCase() == "PASSWORD") {
            return true;
        } else {
            return false;
        }
    };
}
document.ondragstart = function() {
    return false;
};
/*]]>*/
</script>
```

**Comment by krystian3w** [comment]
```css
.blogger .format-quote{ padding:40px 60px 60px !important;pointer-events:none; border-width:0 !important;}
```
