### ISSUE TITLE
bogdankaminski.pl

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#6194]
⚠️ website have vomiting preloader, so use this to disable:

```
bogdankaminski.pl,serwer1695147.home.pl###robactwo:not([style])
```

---

### url

`http://bogdankaminski.pl/`
`http://serwer1695147.home.pl/bogdankaminski/`

### problem

block selet / copy with CSS3

 `view-source:http://bogdankaminski.pl/styles/common.css`
 `view-source:http://serwer1695147.home.pl/bogdankaminski/styles/common.css`

```css
/*Dotyczy każdego id oraz znacznika*/
* {
	padding: 0px;
	margin: 0px;
	-webkit-touch-callout: none;
	-webkit-user-select: none;
	-khtml-user-select: none;
	-o-user-select: none;
	-moz-user-select: none;
	-ms-user-select: none;
	user-select: none;
}
```
