### ISSUE TITLE
badzjeszczelepszy.pl

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#6365]
### URL:

```
https://www.badzjeszczelepszy.pl/tematy-do-rozmowy
```

---

### Problems:

- blocked select any text by JavaScript 

- fake paywall at botom of posts:
   - blured text
   - color text changed to transparent
   - added shadow with CSS to mislead users
   - also blocked selection with CSS (maybe when user disable all JS)

   ```css
   .ga-blur-3349,
   .ga-blur-3349 img {
    color: transparent;
    text-shadow: 0 0 17px rgba(0,0,0,0.5);
    filter: blur(17px);
    -webkit-filter: blur(17px);
    -moz-filter: blur(17px);
    -o-filter: blur(17px);
    -ms-filter: blur(17px);
    filter:progid:DXImageTransform.Microsoft.Blur(PixelRadius='17');
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -khtml-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
   }
   ```

- Links `[href="https://www.badzjeszczelepszy.pl/"]` open other website:

   ```
   http://korneltomicki.getleads.pl/randki/
   ```

   Maybe scam...

---

# Screenshoots

![obraz](https://user-images.githubusercontent.com/35370833/65824182-f960fa00-e264-11e9-8ec5-e8eee4aa4552.png) |
---- |

![obraz](https://user-images.githubusercontent.com/35370833/65824235-c408dc00-e265-11e9-98cc-0b2c0ae65564.png) |
--- |
