### ISSUE TITLE
mountaintopwebdesign.com

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#6398]
`https://mountaintopwebdesign.com/is-google-punishing-sites-without-ssl-certificates/`

newsletter pop-up with locked scrolling:

![obraz](https://user-images.githubusercontent.com/35370833/66240703-a8865100-e6fd-11e9-8d8b-7456e87ac0c3.png) |
--- |

`###wmpci-popup-wrp`

```css
wmpci-popup-open, .wmpci-popup-open body {
    overflow: hidden;
}
```
