### ISSUE TITLE
bindingofisaac.fandom.com

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#7398]
`https://bindingofisaac.fandom.com/wiki/The_Nail`

Annoyance CSS3 "animation" on hover links:

> `https://caniuse.com/css-transitions`, `https://caniuse.com/#feat=css-transitions`

```css
a:hover {
    text-shadow: 0 0 2.5px #800000,0 0 2.5px #800000;
    color: #800000 !important;
    text-decoration: none;
    -webkit-transition: all .4s linear 0s;
    -moz-transition: all .4s linear 0s;
    -ms-transition: all .4s linear 0s;
    -o-transition: all .4s linear 0s;
    transition: all .4s linear 0s;
}
```

Maybe should be disabled with CSS?

filter:
```
bindingofisaac.fandom.com#$#a:hover { text-shadow: none !important; -webkit-transition: none !important; -moz-transition: none !important; transition: none !important; }
```

---

`-o-` omitted because:

 uBO no have active fork for Opera 10-12 <sup>(Presto engine, pre-blink/chromium)</sup> - <sup>`https://forums.opera.com/topic/14755/ublock-origin-for-opera-12-presto`</sup>.

`-ms-` omitted because:

> IE10 (the first stable version of IE to support transition) does not require the -ms- prefix.

older no support at all.
